### ISSUE TITLE
 Step 5/9: Geographic Coverage 

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#102]
Bonjour

Je me suis amuse à charger votre jeu d'essai sur la version de test.

C'est normal que ces cases ne soient pas remplies. Vous n'avez pas rentré de valeurs ?

![image](https://user-images.githubusercontent.com/29607993/85018366-5abb5700-b16d-11ea-869d-1e9fd9c6d50b.png)

PS : j'ai découvert que l'on pouvait mettre plusieurs varaibles au niveau de site_lat et site_long et que ca ne choquait pas  le logiciel même quand on disait "proceed"
![image](https://user-images.githubusercontent.com/29607993/85018618-c4d3fc00-b16d-11ea-9dfb-c9c883e8368f.png)

Ces cases sont vides aussi

![image](https://user-images.githubusercontent.com/29607993/85018800-0e244b80-b16e-11ea-9269-6288d9892f7c.png)

**Comment by earnaud** [comment]
Concernant le fait que les cases soient vides:
- dans le geographic coverage: oui, je pourrais au moins trouver les colonnes commençant par "lat" ou contenant "latitude". Ce n'est pas forcément compliqué mais je n'ai pas forcément eu le temps de développer tous les détails
- dans le personnel: il est très rare que les métadonnées des fichiers contiennent les identités des personnes ayant contribué au projet

Et concernant les doubles colonnes: oui, cela ne choque pas MetaShARK car ces valeurs doivent être comprises entre -180 et 180, ce qui n'est donc pas anormal. Les tests auront peut-être moyen d'être plus poussés à l'avenir.

**Comment by earnaud** [comment]
Comme ce ne sont pas des fonctionnalités "buggées", je ferme l'issue.

**Comment by quidoz** [comment]
Euh …. Ce que je voulais dire que dans l’exemple qui est sur le serveur ces données sont absentes, donc soit l’exemple n’est pas allé jusqu’à la 9ième étape, soit les valeurs n’ont pas été sauvegardés. N’ayant aucune possibilité de savoir dans quel cas je suis, je vous ai envoyé un message au cas ca serait un bug

De : earnaud <notifications@github.com>
Envoyé : jeudi 18 juin 2020 16:54
À : earnaud/MetaShARK-v2 <MetaShARK-v2@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [earnaud/MetaShARK-v2] Step 5/9: Geographic Coverage (#102)


Comme ce ne sont pas des fonctionnalités "buggées", je ferme l'issue.
