### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#103]
C'est pour faire un lien avec les ontologies ?

![image](https://user-images.githubusercontent.com/29607993/85019433-221c7d00-b16f-11ea-8048-9125ff4b67ee.png)

**Comment by yvanlebras** [comment]
Oui tout à fait. Pour le moment, Élie à développer un package R nommé cedarr pour accéder facilement aux contenus des ontologies de Bioportal via l'API cedar qui nous semble LE bon canal... Et le module Annotate est un module permettant d'utiliser le package cedarr via interface graphique. Pour le moment, il faut avoir une clé d'api cedar pour l'activer, donc utilisable en local mais pas encore en serveur car on ne gère pas (encore) les sessions utilisateurs via le mode serveur de MetaShARK.

**Comment by yvanlebras** [comment]
Quand je dis Bioportal c'est vraiment tous les termes de toutes les ontologies ici https://bioportal.bioontology.org/ on souhaite aussi dans le futur pouvoir ajouter Agro et eco portal en espérant pouvoir employer les mêmes méthodes / scripts.

**Comment by earnaud** [comment]
Voir #28
