### ISSUE TITLE
Error writing geographic coordinates

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#104]
It appears there is an issue when MetaShARK writes longitude and latitude coordinates on the geographic_coverage.txt, it seems 1/ it duplicates first coordinate to each line and 2/ takes latitude first and second lines to fill each information instead of taking first line latitude and longitude content to fill first observation latitude and longitude information, and same for next line etc...
Here is an example of the filled geographic_coverage.txt file
![image](https://user-images.githubusercontent.com/7910679/85457621-880a6980-b5a0-11ea-89d7-41fe419c94ca.png)
and the original data fiel with longitude and latitude attributes
![image](https://user-images.githubusercontent.com/7910679/85457785-b5efae00-b5a0-11ea-9742-95bd7c97dca9.png)

Duno if this is a MetaShARK issue or a EML-AL one @clnsmth

**Comment by clnsmth** [comment]
@yvanlebras this appears to be a MetaShARK issue. I just tested `template_geographic_coverage()` and it's working as expected.

**Comment by earnaud** [comment]
Indeed, as geographic coverage was one of my last changes, it might be (and surely is) my bad.
