### ISSUE TITLE
Demo installation is offline

### ISSUE THREAD

**Issue by timrobertson100** [earnaud/MetaShARK-v2#110]
The intro in the readme points to https://metashark.pndb.fr/ but this seems to return 503. Is it possible to fix the instance to explore, please?
Thanks

**Comment by yvanlebras** [comment]
Hi Tim, Hope all is doing well on your side!

Sorry, we changed the URL of the test instance to https://metashark.test.pndb.fr/  and don't change it on doc. Don't hesitate to come back for any question / comments !

Whishing you a good end of day,

Best,

Yvan

**Comment by timrobertson100** [comment]
Thanks @yvanlebras 
I am well thanks - hope you are too!
