### ISSUE TITLE
New MetaShARK version: Facilitate identification of fields user must fill in Fill In module

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#112]
As it seems hard to 1/ know for which attribute the user must specify something and 2/ when on the attribute, maybe we can have a specific colored tet + bold to indicate whuch content the user must fill ?

![image](https://user-images.githubusercontent.com/7910679/98296463-3f81a480-1fb3-11eb-9740-583100dca6db.png)

**Comment by earnaud** [comment]
{shinyfeedback} might have some difficulties on server and in nested modules.

**Comment by earnaud** [comment]
Well, this bugs reveal a more important one concerning inputs IDs.
