### ISSUE TITLE
Summer version 1.4: attribute preview not working properly

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#120]
In the Fill In module, it appears that the "attribute preview" from the step 2 "Attributes" don't show content of the "column" . MetaShARK indicates "empty attribute" but there is content on it.
![image](https://user-images.githubusercontent.com/7910679/100596953-17107000-32fd-11eb-9e60-d21e5dd37a89.png)

MAybe due to some empty "cells" on the attribute column ?

Moreover, for the "expertise_expert_date" attribute, for this attribute preview, there is an error message "argument is not a character vector"
![image](https://user-images.githubusercontent.com/7910679/100597061-3effd380-32fd-11eb-9fc0-fb12d0f8a725.png)

Once that says, this can also be due to a bad formatting of the file.... I need to investigate this also!

**Comment by yvanlebras** [comment]
In fact, it seems that when first "cell" is empty, MEtaShARK says that the attribute is empty, even if others cells are filled + when the first "cell" is filled, here is the error code "argument is not a character vector". So it appears there is an issue with the data format of the file: `2015-01-21`

**Comment by earnaud** [comment]
It is surely due to some problem of encoding: if a value begins with a non-recognized symbol, this value is read as "" (like a non-recognized symbol occurring in the middle of a word breaks this word). Well, concerning dates, I do not get why this occurs.
