### ISSUE TITLE
MetaShARK winter edition: After completing a DP, creating a new one and going to the first "data upload step" shows previous DP related data

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#132]
Here I tested creation of a DP for the "BDD_Kakila_v2_20201217_taxon.tsv" file. Then , after generating the EML, I click on "Quit"(save and Quit). In the Fill in "home page", I specify a new project and DP name, then click on next to have a possibility to upload a dataset, but here appears the dataset I uploaded for the DP I just created before (so "BDD_Kakila_v2_20201217_taxon.tsv") :

![image](https://user-images.githubusercontent.com/7910679/114271691-ef4fb800-9a12-11eb-931f-1af656f35b78.png)

**Comment by earnaud** [comment]
Related to #133

**Comment by yvanlebras** [comment]
So, fixed ? Youhouhou !
