### ISSUE TITLE
Taxonomic coverage display only one authority being queried if 2 are selected

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#168]
If we select 2 authjorities, the GUI display only one:

![image](https://user-images.githubusercontent.com/7910679/137131301-8e47cb27-4104-4786-af52-7c75a1a7e243.png)

But in the resulting EAL files (and EML), both authorities have been used! So it appears to be "just" a display message error ;)

**Comment by earnaud** [comment]
noticed. I think we already encountered the bug, but did not fix it. I will get on it.
