### ISSUE TITLE
Improvement: add a language tag on the EML

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#180]
It can be of interest to add this tag, maybe proposing "by default" "eng" like this:
```
  </pubDate>
  <language>eng</language>
    <abstract>
```
And maybe propose a way in MetaShARK to change it if needed (but ITM very rare I guess)

**Comment by yvanlebras** [comment]
And... as it appears to me this is the metadata language used, it can be "just" indicated as eng! If needed to modify, users can do it manually.

**Comment by earnaud** [comment]
Seems like something to do in EAL before MetaShARK ;)
