### ISSUE TITLE
There is no package called 'tagsinput'

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#19]
On the fill EML through EML-AL module, once we fill contact and creator informations, we have this error

![image](https://user-images.githubusercontent.com/7910679/74584864-0c3b5780-4fd7-11ea-9264-27cf2d80de64.png)

Apparently this is related to this R script https://github.com/earnaud/MetaShARK-v2/blob/master/R/mod-emlal-EMLAL_misc.R#L43

**Comment by earnaud** [comment]
Fixed.
