### ISSUE TITLE
Propose automatic filling of datapackage name

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#22]
In the Data PAckage Name, there is a value indicated, and it appears that maybe, this can be a "default value" but rendreing it unique so if you write pacakges the same day you have automatic package naming with unique ID (something like 2020-02-19_01) and if you want to change something, you have to click on the form and write the package name you want

![image](https://user-images.githubusercontent.com/7910679/74837745-77ac5e80-5322-11ea-8143-b7850f722cd9.png)

**Comment by earnaud** [comment]
Fixed in #72
