### ISSUE TITLE
Infer geographic coverage from 2 columns (lat and long)

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#23]
When giving only one column for lat and one column for long, if these columns are related to a physical uniq geographical point by row, MEtaShark must compute all values and creates automagically the related polygon (or all points or something like this)

**Comment by earnaud** [comment]
(re-reading this issue) Isn't it done yet? Or I do not understand ... the polygon will be drawn according to geographic coverage while writing the EML I think. I'll check it.

**Comment by earnaud** [comment]
Fixed in #34
