### ISSUE TITLE
EAL `make_eml()` does not work

### ISSUE THREAD

**Issue by earnaud** [earnaud/MetaShARK-v2#26]
One may experience troubles upon using `EMLassemblyline::make_eml()` within MetaShARK. This is a dedicated topic, reachable from the app in case of error.
**Contributing to this topic:**

1. `CTRL+F` your error message. If you already find it, juste comment or react to mean you also got the error: it will increase its priority.
2. If you didn't find your error message already reported, add a new message and cite @earnaud or @clnsmth in order to fix the bug or tell you what went wrong. In your message, do not forget to mention whether you were using local or server version.
3. If possible, tell us where we could find the data files you used to be able to reproduce the bug.

**Comment by earnaud** [comment]
Last met bug: 
I filled the `data.description` with the `data.table`'s content ( c("decomp.csv", "nitrogen.csv") ).
`Error in validate_arguments(fun.name = "make_eml", fun.args = as.list(environment())) : 
  Input argument "data.table.description" is missing.`
But not filling this argument returns:
`Error in make_eml(path = paste(.$SelectDP$dp_path, .$SelectDP$dp_name,  : 
  unused argument (data.description = .$DataFiles$dp_data_files$name)`

**Comment by yvanlebras** [comment]
Léa maybe encounter this type of issue ?

**Comment by earnaud** [comment]
`make_eml()` examples fail to validate.

**Comment by clnsmth** [comment]
Thanks for reporting this @earnaud. Try using `data.table.description` instead of `data.description`. Does that fix the error?

**Comment by earnaud** [comment]
Another case: 

I accessed different error levels (with the miraculous help of the `recover()` function !). Here are the results:
```
[call to make_eml()]
Making EML ...
Error : $ operator is invalid for atomic vectors
In addition: Warning messages:
1: Defaulting argument 'data.table.name' to 'data.table'. Consider providing a brief descriptive name for your file(s). 
2: Consider annotating your metadata. Annotations provide precise meaning thereby improving human and machine understanding. Use the template_annotations() function to create the annotations.txt template. 
```
`recover()` allowed me to discover that the failing field was `x$template$personnel.txt$content` :
```
Browse[1]> x$template$personnel.txt$content
[1] NA
```
BUT, `personnel.txt` is not empty:
```
givenName	middleInitial	surName	organizationName	electronicMailAddress	userId	role	projectTitle	fundingAgency	fundingNumber
Yvan	""	Le Bras	MNHN	yvan.le-bras@mnhn.fr		creator			
Yvan	""	Le Bras	MNHN	yvan.le-bras@mnhn.fr		contact	
```

**Comment by clnsmth** [comment]
Thanks for this report @earnaud!

I inspected the linked files and found a few issues that I've fixed ([2020-02-24_test_emldp_fixed.zip](https://www.dropbox.com/s/cyll5q3n57kcbmt/2020-02-24_test_emldp_fixed.zip?dl=0) and [makeemltest_fixed.txt](https://www.dropbox.com/s/5ldg2tqcib5kwyp/makeemltest_fixed.txt?dl=0)):

1.) Not all the EAL metadata templates are located at `path`. I've fixed this by adding the templates in **./2020-02-24_test_emldp** to **./2020-02-24_test_emldp/2020-02-24_test/metadata_templates**.

2.) The `make_eml()` arguments `user.id` and `user.domain` were missing. I've added these.

3.) Definitions were missing from the table attributes templates. I've added some default text.

Issue 1 occurs because EAL doesn't check and report missing templates when `make_eml()` is run. This fix is underway ([see EAL issue 35](https://github.com/EDIorg/EMLassemblyline/projects/1))!

Issues 2 and 3 occur because EAL requirements have not yet been relaxed. I understand that relaxing these requirements to allow greater variation in the inputs to `make_eml()` is important for MetaShARK and has a high priority in the list of current EAL issues ([see EAL issue 34](https://github.com/EDIorg/EMLassemblyline/projects/1)).

**Comment by earnaud** [comment]
Get the following error:
```
Error in compile_attributes(x = x) : 
  The number of attributes listed in  attributes_decomp.txt  does not match the number of columns listed in the corresponding data table. Please correct this. 
```

**Comment by earnaud** [comment]
Fixed in #34 ! Thanks @clnsmth for your help ! However, I keep the issue open for the next few weeks of test.

**Comment by clnsmth** [comment]
Great @earnaud! Yes, let's leave the issue open for any unexpected surprises.

**Comment by earnaud** [comment]
New issue after upgrading EAL to its last version. I had this error message:
```
Error in if (!any(use_i)) { : missing value where TRUE/FALSE needed
```
It seems the `attr.template` called through an EMLassemblyline template is not properly structured as one of its columns ('core_template' or sthg like this) is called in `template_arguments()` but is not defined before.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @earnaud. I'm unable to reproduce the reported error using the reprex files (i.e. **2020-02-24_test_emldp.zip**). Is there a different set of files I should be working with?

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] EMLassemblyline_2.10.1

loaded via a namespace (and not attached):
 [1] zoo_1.8-7            tidyselect_1.0.0     xfun_0.12           
 [4] reader_1.0.6         taxize_0.9.92        purrr_0.3.3         
 [7] lattice_0.20-38      V8_3.0.2             vctrs_0.2.4         
[10] htmltools_0.4.0      yaml_2.2.1           rlang_0.4.5         
[13] pillar_1.4.3         glue_1.3.2           httpcode_0.2.0      
[16] solrium_1.1.4        uuid_0.1-4           foreach_1.4.8       
[19] lifecycle_0.2.0      plyr_1.8.5           NCmisc_1.1.6        
[22] stringr_1.4.0        codetools_0.2-15     evaluate_0.14       
[25] knitr_1.28           emld_0.4.0           curl_4.3            
[28] parallel_3.5.2       fansi_0.4.1          triebeard_0.3.0     
[31] urltools_1.7.3       EDIutils_1.1.2       Rcpp_1.0.4          
[34] jsonlite_1.6.1       digest_0.6.25        stringi_1.4.6       
[37] jsonld_2.1           proftools_0.99-2     ritis_0.8.0         
[40] dplyr_0.8.5          taxonomyCleanr_1.2.0 grid_3.5.2          
[43] jqr_1.1.0            cli_2.0.2            tools_3.5.2         
[46] magrittr_1.5         lazyeval_0.2.2       tibble_3.0.0        
[49] bold_0.9.0           EML_2.0.2            crul_0.9.0          
[52] crayon_1.3.4         ape_5.3              pkgconfig_2.0.3     
[55] ellipsis_0.3.0       data.table_1.12.8    xml2_1.2.5          
[58] iterators_1.0.12     assertthat_0.2.1     rmarkdown_2.1       
[61] reshape_0.8.8        rstudioapi_0.11      R6_2.4.1            
[64] nlme_3.1-137         compiler_3.5.2      
> 
> 
> library(EMLassemblyline)
> setwd("~/dataPackagesOutput/emlAssemblyLine/reprex_emldp/reprex_emldp/reprex/")
> path <- paste0(getwd(), "/metadata_templates/")
> data <- paste0(getwd(), "/data_objects/")
> eml <- paste0(getwd(), "/eml/")
> 
> # Create the list of inputs to EMLassemblyline
> 
> x <- template_arguments(
+   path = path,
+   data.path = data,
+   data.table = dir(data))
> 
> # Manually add arguments to x
> 
> x$path <- path
> x$data.path <- data
> x$eml.path <- eml
> x$data.table <- c('decomp.csv', 'nitrogen.csv')
> x$data.table.name <- c('Decomposition data table', 'Nitrogen data table')
> x$data.table.description <- c('Description of the decomposition data table', 'Description of the nitrogen data table')
> x$dataset.title <- "Dataset title"
> x$maintenance.description <- "Complete"
> x$package.id <- "SomepackageID"
> x$return.obj <- TRUE
> x$temporal.coverage <- c('2014-05-01', '2015-10-31')
> x$user.domain <- "UserDomain"
> x$user.id <- "UserID"
> x$write.file <- TRUE
> 
> # Unused arguments must be removed from x
> 
> x$geographic.coordinates <- NULL
> x$geographic.description <- NULL
> 
> # Call make_eml()
> 
> output <- do.call(make_eml, x[names(x) %in% names(formals(make_eml))])
Making EML ...
Creating nodes ...
<eml>
  <access>
  <dataset>
    <title>
    <creator>
    <pubDate>
    <abstract>
    <keywordSet>
    <keyword>
   <additionalInfo>
    <intellectualRights>
    <coverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <geographicCoverage>
      <temporalCoverage>
      <taxonomicCoverage>
    <maintenance>
    <contact>
    <methods>
    <dataTable> (decomp.csv)
    <dataTable> (nitrogen.csv)
</eml>
Writing EML (SomepackageID.xml)
Validating EML
EML passed validation!
Done.
Warning messages:
1: Input argument "user.domain" is not "EDI" or "LTER". If not creating a data package for EDI, then ignore this message. A default value "someuserdomain" will be used. 
2: Input argument "package.id" is not valid for EDI. An EDI package ID must consist of a scope, identifier, and revision (e.g. "edi.100.4"). If not creating a data package for EDI, then ignore this message. 
3: Argument 'data.url' is deprecated; please use 'data.table.url' and 'other.entity.url' instead. 
> 
```

**Comment by earnaud** [comment]
Hi Colin, 

the bug has gone as it appeared. However, I did not understand what it was.

**Comment by clnsmth** [comment]
@earnaud turns out bugs don't miraculously disappear : )

The one you reported was related to NA values in EAL metadata templates where make_eml() wasn't expecting them. I've implemented an enhancement in the development and master branches that ignores these extraneous NAs ([EAL 2.11.0](https://github.com/EDIorg/EMLassemblyline/commit/dee359348c0670039d478da87030490eebad8164#diff-e1e1d3d40573127e9ee0480caf1283d6)).

**Comment by earnaud** [comment]
New error message occured yesterday:
`Element 'enumeratedDomain': Missing child element(s). Expected is one of ( codeDefinition, externalCodeSet, entityCodeList ).`
@clnsmth I am investigating about it. Any idea or previous experience? Note that in dev mode, I can see this message appear 9 times. Is attached the DP I wrote: I don't see problems in the metadata templates content. 
The error message originates from the {EML} package.

[2020-04-16_project.zip](https://github.com/earnaud/MetaShARK-v2/files/4509135/2020-04-16_project.zip)

**Comment by clnsmth** [comment]
Thanks @earnaud! This issue is arising because EML doesn’t accept empty strings (i.e. “”) as categorical variables in the `/nominal/nonNumericDomain/enumeratedDomain/codeDefinition/code` node. Relatedly, empty strings are not allowed as missing values in the `/missingValuecode/code`.

If these data can be modified prior to creating EML then the recommendation is to fill these empties with “NA” or some other missing value code.

If these data cannot be modified then you could change the class of these attributes from “categorical” to “character” in the table attributes template (i.e. change it to  `/nominal/nonNumericDomain/textDomain`) and define the meaning of the empty values in the attribute definition. Adding a descriptor in the code field like "(empty value)" to describe an empty value is strongly discouraged.

What should the default behavior of EMLassemblyline be when empty values are encountered? One option is for it to change the class of this attribute to character and send a warning message to alert the user of the issue with recommendations for fixing it.

[Here’s more discussion on this topic](https://github.com/NCEAS/eml/issues/299).
