### ISSUE TITLE
Welcome and EML hyperlink not relevant ?

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#40]
When we click on "Ecological Metadata Language" hyperlink on the welcome page

![image](https://user-images.githubusercontent.com/7910679/77085737-0c2cde00-6a01-11ea-9a48-47d89d5fe1b1.png)

this raises to http://openstack-192-168-100-116.genouest.org/#EML ... Is it normal ?

**Comment by earnaud** [comment]
Corrected in next push
