### ISSUE TITLE
EML Documentation module & nothing append clicking on "Go" Button

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#41]
Nothing appears clicking on the Go Button from the EML doc module. MAybe just due to the server version on 116 openstack VM ?
![image](https://user-images.githubusercontent.com/7910679/77085956-5a41e180-6a01-11ea-8382-5fba55d917fa.png)

**Comment by earnaud** [comment]
It might have happened. This feature was originally yet a little buggy. I think I will restrict it to a simple link to main documentation: https://eml.ecoinformatics.org/schema/

**Comment by yvanlebras** [comment]
Totally agree !
