### ISSUE TITLE
exchange between KNB and NCEAS terms ?

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#42]
In the welcome module, it appears to me that maybe, there is an inversion between mentions of KNB and NCEAS in this sentence : `Since then, it has been developped by the NCEAS (National Center for Ecological Analysis and Synthesis) and is mainly accessible through the KNB (Knowledge Network for Biodiversity) and its git` as git hyperlink is the NCEAS github link... Isn't it ?

**Comment by earnaud** [comment]
Indeed

**Comment by earnaud** [comment]
Corrected in next push
