### ISSUE TITLE
Detect missing value presence & code

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#44]
Having a manner to determine missing value (NA or others) and indicating the corresponding code to EML attributes missing value field

**Comment by earnaud** [comment]
Reviewing the issues: what is the point of this one? Is the "missing value code" feature of EML not enough?

**Comment by yvanlebras** [comment]
In fact, it appears to me there is solutions, R packages, to propose the missing value code (so to automatically filling this EML field) for each column. You can have a look ? Or ""we"" can create a simpl eR script who looks at each columns and if there is common missing value code like NA, #NA, .. automatically fill the corresponding field.

**Comment by earnaud** [comment]
I think this has been adressed at EAL level.
