### ISSUE TITLE
PRoviding ORCID id -> Freeze of web version

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#48]
Pasting this 0000-0002-8504-068X to the ORCID field make the metaShARK web version freezing...

**Comment by yvanlebras** [comment]
now this is ok, BUT it seems the "web" version of MetaShARK is not configured to use rorcid directly

**Comment by earnaud** [comment]
Could you detail the issue?

**Comment by yvanlebras** [comment]
so the "freeze" issue is solved now. BUT using 116 metashark web version, if I copy/paste my orcid, nothing happen... so I think that this is just that rorcid is not allowed on the VM to take orcid nifo for metashark.
