### ISSUE TITLE
USe welcome page to explain the MEtaShARK procedure

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#51]
Maybe presenting the entire workflow with a figure and each step with texts ?

**Comment by earnaud** [comment]
Each step has a "help" button. But I could add a "How to use" paragraph at some place

**Comment by yvanlebras** [comment]
True that the "Help" buttons are really tip top !!! Thank you. SO maybe this Emilie comment is more to have a place to synthetize in one figure the Fill In procedure (maybe just presenting the 9 steps ?)?

**Comment by earnaud** [comment]
I shall had some minor improvements in the UI and to explain what the user shall expect.
