### ISSUE TITLE
Consider minimize or move "about EML AL" section

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#52]
It take a lot of place for not a lot of important info. MAybe consider having it only on the first step of Fill In EML ? Or move at the bottom ? Or move on the "about" page ?

**Comment by earnaud** [comment]
I think it is important to acknowledge the authors. But I shall move it on the Welcome page.

**Comment by yvanlebras** [comment]
In fact this is an Emilie feedback, and maybe she doesn't see that we can minimize it ... As it appears to me this is ok when minimized... Maybe automatically minimized it after step1 ?
