### ISSUE TITLE
On "Data table attributes" section, expand a particular attribute form clicking on the entire "block" not only text

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#54]

**Comment by earnaud** [comment]
This depends on the `{shinyBS}` package and cannot be modified from MetaShARK. I might fork it if their team is not active. 
See [this issue](https://github.com/ebailey78/shinyBS/issues/122)

**Comment by yvanlebras** [comment]
Perfect! Thank you!
