### ISSUE TITLE
Precise unitType on fill in EML datable attribute section

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#55]
Instead of having a list of units, maybe consider having the same list but with UnitType/Unit (ex: Angle/Degree) for each element ?

**Comment by yvanlebras** [comment]
... and there is also description who can be used https://docs.ropensci.org/EML/reference/get_unitList.html maybe displaying it when putting the mouse on the unit ?

**Comment by earnaud** [comment]
If I don't mistake myself, this list is already used in MetaShARK.

**Comment by yvanlebras** [comment]
yes, but "only" with one term, not others related info (UnitYpe/Unit and why not description ...)
