### ISSUE TITLE
Fill in EML contacts step ameliorate respective visibility of creator and contact on each block

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#56]

**Comment by yvanlebras** [comment]
A proposition can be to "just" ameliorate the display of each role by block. Antoher proposition can be to have "only" one ""table"" with a "role" column with 3 choices (creator/contact/creator and contact) with a control on what is filled to be sure that we have at leats a creator and a contact...

**Comment by earnaud** [comment]
I know this module can (and will) be improved. To this, I think about:
- [ ] editing each box dynamically (with role, and maybe name)
- [ ] make a box for each role
- [ ] add a person with a mini dialog box asking for the role and the Orcid or name
