### ISSUE TITLE
Documentation freeze

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#58]
When trying to click on a term on the "tree"
```
Warning: Error in <Anonymous>: No handler registered for type documentation-tree:shinyTree
  [No stack trace available]
Error in (function (name, val, shinysession)  : 
  No handler registered for type documentation-tree:shinyTree
```

**Comment by earnaud** [comment]
Ok, either weird things happen there, either I have forgotten somethin but: a variable named "tree" is defined as a package variable. It is a list containing all of the EML spec. Investigating ...

**Comment by earnaud** [comment]
Ok, the issue seems to happen if the doc is opened too quickly upon reaching the documentation module. Let some time for the doc to be loaded and it shall be ok. 

I let this opened as Documentation re-working will be my next step.

**Comment by yvanlebras** [comment]
Ok now! Thanks !
