### ISSUE TITLE
datafiles attribute of fill in module no indication there is more than one datafile

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#60]
it looks like there is a bug as the "grey/blue" progression bar is working well for categorical attributes (from the firts catvar, there is a percentage of of bar who is blue, 33% if only 3 catvar) but doesnt seems to work with data attribute, if 2 files, when on the first one, the entire bar is grey (and I don't think going on the second file give some blue information on this bar...)

**Comment by earnaud** [comment]
Yep, working on re-writing this
