### ISSUE TITLE
Fill in geographic coverage can't remove a manually "fill geographic coverage"

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#61]
if you specify data attributes for geographic coverage, then going to the fill geographic coverage and cllick on plus you can't remove this "manual" created " geographic edition box. and MetaShARK is then not allowing you to go further (nothing appen clicking on the NExt button)

**Comment by earnaud** [comment]
Not met in online version nor in local session. Do you fill all of the "column selection" input fields?

**Comment by yvanlebras** [comment]
yes
