### ISSUE TITLE
Possible EMLAL issue taxonomic coverage not written in taxonomic coverage in EML file but only in measurementscale in taxa entity attribute

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#63]
it seems to me that using the taxa column from EMLAL example file allow to 1/ describe this attribute but moreover 2/ complete the taxonomic coverage EML section. Here, the taxonomic coverage is not filled

**Comment by earnaud** [comment]
@clnsmth ?

**Comment by clnsmth** [comment]
Thanks for reporting this @yvanlebras @earnaud. It appears to be a bug in taxonomyCleanr and EMLassemblyline. I'm working on a fix now.

**Comment by clnsmth** [comment]
This issue has been fixed. Please upgrade to taxonomyCleanr 1.3.0 and EMLassembyline 2.12.3.

**Comment by yvanlebras** [comment]
Ouahou! Thank you for your rapid answer Colin! We will test the fix and come back to you to confirm it is ok!
