### ISSUE TITLE
whan adding keywordSet / thesaurus, this apply to all keywords

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#68]
It seems not possible to select which keywords are associated to a special keywordSet

**Comment by earnaud** [comment]
Indeed, there is a single keywodSet produced by now. I shall work on allowing "themed" keywordSet.

**Comment by yvanlebras** [comment]
.... And if you find a way to propose adding terminological resources.... Or maybe this has to be done "only" for each attribute ?

**Comment by earnaud** [comment]
This will be part of a future update, working on both terminological resources and EML2.2.0 "annotations"

**Comment by earnaud** [comment]
A new way to type in keywords has been added, closing this issue for now.
