### ISSUE TITLE
Navigation block improvements : 

### ISSUE THREAD

**Issue by jusana** [earnaud/MetaShARK-v2#70]
- Maybe it would be clearer to have "Next step" or even "to step X/Y"  instead of just "next"
- same for "previous"
- "save" --> save session ? save file ? save state ?  ... what do I save ?

just a few little things i noticed ...

**Comment by earnaud** [comment]
See #51 : I will add this to the "explain MetaShARK procedure"

**Comment by jusana** [comment]
ok, nice !
