### ISSUE TITLE
selection de l'unité

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#74]
Bonjour
Je pense qu'il serait mieux que par défaut la sélection soit positionnée a dimsensionless plutôt qu'au premier de la liste. Faut mieux ne pas avoir d'unité que d'en avoir une mauvaise

**Comment by yvanlebras** [comment]
Hello,

Merci de ton retour! Tout à fait d'accord ! Bien vu!

**Comment by quidoz** [comment]
Bonjour

Dans l'unité à la différence de ce que l'on voir sur la video, j'ai deux valeurs séparés par / qui apparait ?

**Comment by yvanlebras** [comment]
oui, je pense que l'erreur vient de là, c'est une nouvelle fonctionnalité...

**Comment by earnaud** [comment]
Corrigé. Ce bug causaiit aussi celui de `make eml` non-fonctionnel.
