### ISSUE TITLE
Name of organization the person is associated with.*

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#75]
Bonjour
Dans l'étape 7/9 j'ai l'impression que la vérification de la présence de texte dans un champ obligatoire n'est pas sans faille 
PS : ca serait bien de pouvoir dupliquer les contacts

**Comment by yvanlebras** [comment]
Effectivement, on a vu que pour certaines étapes, des champs obligatoires pouvaient ne pas être renseignés et quand même laisser l'utilisateur continuer vers l'étape suivante

**Comment by earnaud** [comment]
La vérification ne se fait effectivement pas dès l'arrivée de l'utilisateur sur l'étape. Je vais revoir ce bug.

**Comment by earnaud** [comment]
Closed due to duplicated #69
