### ISSUE TITLE
make eml

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#77]
Bonjour
Je crois que j'ai planté le systeme en cliquant sur Make EML

**Comment by yvanlebras** [comment]
Oui, cela arrive que Shiny "freeze" a cette étape finale si il y a une erreur... Comme un champ obligatoire non rempli ;) tu dois en théorie avoir un message d'erreur qui s'affiche juste en dessous du bouton "make EML"... Sinon, tu dois au moins pouvoir recharger ton dataset depuis l'interface relancée (un F5 suffit normalement) du module Film In

**Comment by quidoz** [comment]
Bonjour
    
    Pas de message en dessous du bouton "make EML"
    
    Le 28/04/2020 à 19:48, Yvan Le Bras a
      écrit :
    
    
      Oui, cela arrive que Shiny "freeze" a cette étape finale si il
        y a une erreur... Comme un champ obligatoire non rempli ;) tu
        dois en théorie avoir un message d'erreur qui s'affiche juste en
        dessous du bouton "make EML"... Sinon, tu dois au moins pouvoir
        recharger ton dataset depuis l'interface relancée (un F5 suffit
        normalement) du module Film In

**Comment by earnaud** [comment]
Bonjour,

cette erreur a été résolue. Il s'agissait d'un problème au niveau de la sélection des unités.
