### ISSUE TITLE
Step 5/9: Geographic Coverage - save

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#78]
Bonjour
J'ai l'impression que la sauvegarde de Step 5/9: Geographic Coverage ne marche pas. En tout cas toutes les fois que je recharge le fichier c'est vide

**Comment by earnaud** [comment]
J'ai vu en effet quelques bugs dans ce sens dans les retours d'erreur. Je vais corriger cela dans les plus brefs délais - bien que certains jeux de données semblent avoir pu être sauvegardés à cette étape.
