### ISSUE TITLE
shinyTree error

### ISSUE THREAD

**Issue by trafficonese** [earnaud/MetaShARK-v2#79]
I just tried to look at your shinyTree problem from https://github.com/shinyTree/shinyTree/issues/58. 

I see this error quite often just trying to look at the data `doc`:

> Error in writeImpl(text) : 
>   Text to be written must be a length-one character vector

I tried to go through the nodes one by one and got another error for `doc[[2]]$AttributeType$measurementScale$<complexType>`:

> Error: unexpected '<' in "doc[[2]]$AttributeType$measurementScale$<"

And in there is also the first error
`doc[[2]]$AttributeType$measurementScale[["<complexType>"]]$dateTime`:

> Error in writeImpl(text) : 
>   Text to be written must be a length-one character vector

Somehow I dont think its a `shinyTree` error, as the tree gets rendered initially, just when trying to open a node, it triggers the error you mentioned. So I am pretty sure the tree is not correctly formatted.

**Comment by trafficonese** [comment]
The error comes from this line https://github.com/shinyTree/shinyTree/blob/2d45d9ba8a780a200a5c0f27b5ee5240238c23d8/R/init.R#L85

In your case its because you want to assign a list as "class". Here is a simplified example of the error.

```
ret <- structure(list(structure(0, id = "3")), .Names = "")
jsondata <- list(class = list("shiny.tag.list", "list"))
attr(ret, "class") <- jsondata[["class"]]
```

> Error in attr(ret, "class") <- jsondata[["class"]] : 
>   attempt to set invalid 'class' attribute

Do you need both classes? An easy fix for shinyTree would be to always take the first value. This would at least not trigger this error.

**Comment by earnaud** [comment]
Hello ! 
I am sorry for this late answer. Thansk a lot for your research. The solution of taking only the first value works ! It was indeed on this feature I had a bug. Thanks again :)
