### ISSUE TITLE
problem with remove the files

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#81]
J'ai chargé un fichier qui s'appelait station.csv. J'ai vu qu'il y avait une colonne geom_point qui ne me plaisait pas. J'ai donc cliqué sur remove, changer mon fichier et recharger. Et bien, il m'en tient pas compte il y a toujours ma colonne geom_point

**Comment by earnaud** [comment]
Il y a effectivement un bug avec le fait de changer de fichier. Malgré plusieurs jours dessus, je n'ai pas encore capté le souci.

**Comment by quidoz** [comment]
est ce que ca ne vient pas du fait que je garde le même nom de fichier ?

**Comment by earnaud** [comment]
Normalement non. Petite description de ce qu'il se passe là où le bug survient (au moment de charger un fichier):
- je vérifie que le nom du fichier ne soit pas déjà chargé
- je charge le fichier dans une variable à part
- au moment de l'ajouter à la liste des fichiers existants: erreur.

C'est assez déroutant
