### ISSUE TITLE
Not valid ORCID

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#82]
Il me dit que https://orcid.org/0000-0003-2666-2558 n'est pas un valide ORCID ! metacat a lui l'air de l'aimer

**Comment by yvanlebras** [comment]
Oui il y a l'air d'y avoir un pb avec la fonction de récupération des identifiants ORCID... Je laisse Elie regarder et te dire. MERCI du signalement !!!

**Comment by earnaud** [comment]
Merci du retour. Comment cela se comporte-t-il avec juste "0000-0003-2666-2558" ? (si vous n'avez pas le temps, je testerai ça d'ici peu de temps).

**Comment by jusana** [comment]
pour info, c'est pas tjs clair dans les docs, si le http**_S_** fait partie ou non de l'identifiant

**Comment by earnaud** [comment]
See #101
