### ISSUE TITLE
Generate a summary of your data package - render in markdown

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#83]
Bonjour
Il m'a généré le fichier EML du moins c'est ce qu'il me dit car les deux boutons (write emldown et download eml) ne font rien !

**Comment by yvanlebras** [comment]
Hello, si le nom du datapackage que tu as créé est 2020-05-07_project_station tout semble ok. Du coup, pour télécharger le datapackage avec les données, les métadonnées + le draft de data paper, il faut que tu quittes le module de saisie d'eml à la fin de la procédure de génération d'eml et emldown, et du coup tu dois te retrouver sur la première page de création/consultation de datapackage. Là tu sélectionne ton datapackage (`2020-05-07_project_station` par exemple si c'est celui là) et tu cliques sur `Download.zip` et tu devrais tout récupérer en local (draft de data paper dans le dossier `emldown`, fichiers de données dans `2020-05-07_project_station/data_objects`, le fichier métadonnée au format EML dans `2020-05-07_project_station/eml` et les différentes étapes effectuées durant la saisie de métadonnées dans `2020-05-07_project_station/metadata_templates`)

Le bouton write emldown permet de créer le draft de data paper dans le data package et quand cela a fonctionné, le bouton download emldown devient actif et si tu cliques dessus, normalement, le draft de data paper au format html doit se télécharger ce qui semble ne pas fonctionner (peux tu nous dire quel navigateur tu utilises, cela peut jouer... ?)

En tous cas, heureux que tu ais pu créer ton premier EML via MetaShARK, cela mérite une récompense (je crois que tu es la première hors PNDB ;) ), rendez-vous au colloque de lancement pour cela !!!!!

MERCI beaucoup de prendre de ton temps pour ces nombreux tests !!!

**Comment by quidoz** [comment]
Bonjour
    
    J'utilise le plus souvent Firefox. 
    je vais essayer de mettre plus de texte car je ne suis pas convaincu
    par le contenu du datapaper. D'ailleurs ca serait mieux qu'il soit
    aussi en markdown.
    Je peux essayer d'importer mon premier EML dans metacat ?
    Je prends du temps pour tester car vous êtes une étape importante
    pour le "projet fictif" que je met en place au CEFE dans le cadre de
    l'axe thématique "cycle de vie de la donnée".  Mon projet
    "Observatoire Friture_Du_Lac" !
    
    
    Le 07/05/2020 à 21:55, Yvan Le Bras a
      écrit :
    
    
      Hello, si le nom du datapackage que tu as créé est
        2020-05-07_project_station tout semble ok. Du coup, pour
        télécharger le datapackage avec les données, les métadonnées +
        le draft de data paper, il faut que tu quittes le module de
        saisie d'eml à la fin de la procédure de génération d'eml et
        emldown, et du coup tu dois te retrouver sur la première page de
        création/consultation de datapackage. Là tu sélectionne ton
        datapackage (2020-05-07_project_station par exemple
        si c'est celui là) et tu cliques sur Download.zip
        et tu devrais tout récupérer en local (draft de data paper dans
        le dossier emldown, fichiers de données dans 2020-05-07_project_station/data_objects,
        le fichier métadonnée au format EML dans 2020-05-07_project_station/eml
        et les différentes étapes effectuées durant la saisie de
        métadonnées dans 2020-05-07_project_station/metadata_templates)
      Le bouton write emldown permet de créer le draft de data paper
        dans le data package et quand cela a fonctionné, le bouton
        download emldown devient actif et si tu cliques dessus,
        normalement, le draft de data paper au format html doit se
        télécharger ce qui semble ne pas fonctionner (peux tu nous dire
        quel navigateur tu utilises, cela peut jouer... ?)
      En tous cas, heureux que tu ais pu créer ton premier EML via
        MetaShARK, cela mérite une récompense (je crois que tu es la
        première hors PNDB ;) ), rendez-vous au colloque de lancement
        pour cela !!!!!
      MERCI beaucoup de prendre de ton temps pour ces nombreux tests
        !!!

**Comment by earnaud** [comment]
Je reviens sur ce paquet d'issues que tu as laissé Marie-Claude. Désolé de mon mutisme, j'étais assez concentré à ma tâche et à adresser de nombreux bugs provenant en réalité de seulement 2-3 outils. 

Pour le coup, j'avais essayé d'obtenir un rendu markdown, mais ça n'était pas très convaincant. De plus, je doute que la carte du géographique coverage soit bien rendu en markdown. Mais je m'y remettrai.
