### ISSUE TITLE
Step 8/9: Miscellaneous - Associated thesaurus

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#87]
Bonjour
J'ai l'impression que l'on ne peut pas utiliser le retour arrière dans cette case. peut être aussi d'autres touches (en tout cas, je ne fais jeter tout le temps)

**Comment by yvanlebras** [comment]
Oui pour le moment cette fonctionnalité ne permet pas d'ajouter plusieurs thesaurus. Mais Elie est justement en train de travailler sur quelquechose de beaucoup plus "aux petits oignons" ;) rien que pour toi et Eric ;)

**Comment by quidoz** [comment]
Je voulais juste mettre le nom d'un seul thésaurus qui a certes un nom en trois parties "thesaurus de la biodiversite".

**Comment by earnaud** [comment]
Pour le moment, je pense me reposer sur les ressources de CEDAR (cf. le package {cedarr} que j'ai développé ainsi que la page du CEDAR metadatacenter) qui permet d'accéder à de nombreuses ontologies. L'ajout d'un thesaurus "customisé" pourra voir le jour par la suite.
