### ISSUE TITLE
nombreux champs non sauvegardés

### ISSUE THREAD

**Issue by quidoz** [earnaud/MetaShARK-v2#88]
Bonjour
J'ai rechargé mon fichier pour vérifier (j'ai des soucis avec les informations dans le datapaper) et je me suis aperçue que plein de champs n'étaient pas sauvegardés (style unite, style thesaurus - par contre les mots clefs sont préservés). 

![image](https://user-images.githubusercontent.com/29607993/81703939-8744ca80-946d-11ea-8142-1a9a73f88773.png)

**Comment by yvanlebras** [comment]
MERCI de ce nouveau retour ! Le côté sauvegarde / rechargement d'infos a été mis en place il y a peu, et sûrement certains champs peuvent poser problème.. MERCI de nous indiquer ces champs, je ne l'avais pas vu personnellement ! On va regarder cela une fois la MAJ de l'outil d'ajout de ressources terminologiques faite ;)

**Comment by quidoz** [comment]
N'ont pas été sauvegardés
- unite dans l'etape Step 3/9: Attributes  (je persiste à vouloir mettre degre pour latitude !)
- Step 5/9: Geographic Coverage  les trois champs de cette étape
- Step 6/9: Taxonomic Coverage tous les champs de cette étape
- Step 8/9: Miscellaneous le thesaurus associé
- Step 8/9: Miscellaneous Temporal coverage

**Comment by yvanlebras** [comment]
MERCI beaucoup !!
Oui tu as raison de vouloir insister à mettre degre pour latitutde (et longitude d'ailleurs), je l'ai fait de mon côté et cela avait fonctionné a priori... On va regarder tout cela dans le détail !

**Comment by earnaud** [comment]
Pour le thesaurus, c'est normal: la fonctionnalité est encore là en mode "vitrine". Je travaille actuellement à l'intégration des ressources sémantiques avec lesquelles ils seront le plus pertinent. 

Pour le reste, je note bien. Il faut savoir que MetaShARK construit une variable de sauvegarde qu'il faut encore enregistrer régulèrement. Passer d'une étape à l'autre ne sauvegarde pas tout seul car la dernière version de la sauvegarde prenait beaucoup de temps.

Je vais revoir tout ça bientôt.

**Comment by earnaud** [comment]
Revu. Les champs étaient en réalité bien sauvegardés mais pas chargés au relancement de l'application. Ce qui devrait être corrigé dans la prochaine sortie.
