### ISSUE TITLE
Is there an inversion between object name and entity name if several entities uploaded ?

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#89]
As seen here https://openstack-192-168-100-101.genouest.org/metacatui/view/urn:uuid:077e5611-da27-4d71-8517-bf36a754ac60

Is it a MetaShARK error? A EMLAL one? Due to metacat upload?

**Comment by earnaud** [comment]
There was this in MetaShARK. It was ok when I tested it, but you know what this means ;) I will re-check

**Comment by earnaud** [comment]
This issue did not occur anymore.
