### ISSUE TITLE
Propose a way to convert 45,45 to 45.45 for longitude / latitude

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#92]
Or another way as 45,45 content format is not useable in MetaShARK as geographical coverage information...

**Comment by earnaud** [comment]
I checked this, and geographic coverage shall be at convenient format. Any screenshot/example?

**Comment by earnaud** [comment]
Duplicate with #93

**Comment by yvanlebras** [comment]
Looking at my new comment on #93 , this is in fact not a duplicate ;)
