### ISSUE TITLE
Possibility to replace an entity by another once some informations have already be filled on MetShARK

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#93]
Particularly interesting if we see, after filling some informations that some attributes (like latitude/longitude) are written in a bad format (like 45,45 instead of 45.45).

**Comment by earnaud** [comment]
This means editing a step, or am I wrong?

**Comment by yvanlebras** [comment]
And the issue was in fact more related to propose to the user to download  a corrected data files (so not the file he upload but a corrected version)
