### ISSUE TITLE
When custom geographical coverage possibility to enter precise decimal degree info

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#94]
As for now, using slider we can not really be precise, ""only"" ~1 degree precision.

**Comment by earnaud** [comment]
Indeed no: you shall be able use your keyboard arrows to input more precise number.

**Comment by yvanlebras** [comment]
Oh oh, I was not knowing that we can use the arrows! Maybe can be of interest to add this "tips" somewhere on the GUI ? After saying that, not so easy to use if we need to go more than .5 but this works! Nice !!!
