### ISSUE TITLE
Cannot use MetaShARK locally

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/MetaShARK-v2#96]
MetaShARK V2 installé en local (version "master' et "dev" -> message d'erreur au lancement :
```
ERROR: cannot open file 'C:/Users/ylebras/Documents/R/win-library/3.5/MetaShARK/R/sysdata.rdb': No such file or directory
```

sur la console R j'ai :
```
Warning: Error in docUI: cannot open file 'C:/Users/ylebras/Documents/R/win-library/3.5/MetaShARK/R/sysdata.rdb': No such file or directory
  64: docUI
  46: ui
```

**Comment by earnaud** [comment]
On va dire que c'est une pratique découragée, mais je me mettrai à la tâche de rendre ça possible un jour. Mais ce n'est pas une priorité pour le développement.

**Comment by earnaud** [comment]
Done with dockerization
